version: "3.7"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - flowih-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flowih
    networks:
      rede:
        ipv4_address: 10.6.0.5

volumes:
  flowih-data:
networks:
  rede:
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.0.0/16
         gateway: 10.6.0.1



